---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

params:
  NEW_RELIC_ID:
  NEW_RELIC_KEY:

inputs:
- name: pipeline

outputs:
- name: new_relic_payload

run:
  path: pipeline/ci/scripts/logsearch/check_health.sh

