---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/alpine-ci-tools
    tag: v0.0.6


inputs:
  - name: pipeline
  - name: config
  - name: metadata

outputs:
  - name: output      # For debugging purposes, uncommeny

run:
  path: pipeline/ci/scripts/deploy-status-notification.sh
