---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/ci-tools
    tag: v0.1.7

params:

inputs:
  - name: pipeline
  - name: config
  - name: backup

outputs:


run:
  path: pipeline/ci/scripts/restore.sh
